ALTER TABLE APP.PURCHASE DROP CONSTRAINT PURCHASECUSTOMERID
ALTER TABLE APP.PURCHASE DROP CONSTRAINT PRCHSDLVRYCMPANYID
ALTER TABLE APP.PURCHASE_ITEM DROP CONSTRAINT PRCHASEITEMPRDCTID
ALTER TABLE APP.PURCHASE_ITEM DROP CONSTRAINT PRCHSEITEMPRCHSEID
DROP TABLE APP.CUSTOMER
DROP TABLE APP.PRODUCT
DROP TABLE APP.PURCHASE
DROP TABLE APP.PURCHASE_ITEM
DROP TABLE APP.Delivery_company
